# Generated by Django 4.1.5 on 2023-06-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0002_alter_articles_username_alter_questions_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
