# Generated by Django 4.1.5 on 2023-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0003_categories_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='username',
        ),
        migrations.AddField(
            model_name='articles',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
