# Generated by Django 4.1.5 on 2023-06-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0004_remove_articles_username_articles_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='category_id',
            new_name='category',
        ),
    ]
