# Generated by Django 4.1.5 on 2023-06-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0005_rename_category_id_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(max_length=250),
        ),
    ]
