# Generated by Django 4.1.5 on 2023-06-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0006_alter_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
