# Generated by Django 4.1.5 on 2023-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0009_alter_articles_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemesQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('time_create', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='questions',
            name='theme',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
